source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'Swifit_Rx' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
use_frameworks!
    pod 'RxSwift'
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'SnapKit'
    pod 'RxCocoa'
    pod 'IQKeyboardManagerSwift'
    pod 'MJRefresh'
    pod 'SCLAlertView'
    
  # Pods for Swifit_Rx

  

end
